# Welcome to Serverless!

service: ssff-0167-informe

custom:
  tableName: 'ssff-informe'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  memorySize: 2048
  timeout: 15
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:us-west-2:140176884735:table/ssff-informe"
        - "arn:aws:dynamodb:us-west-2:140176884735:table/ssff-informe-resumen"
  environment:
    tableName: ${self:custom.tableName}

plugins:
  - serverless-offline

functions:
  app:
    handler: handler.generic
    events:
      - http: ANY /        
      - http: ANY {proxy+}